name: 'trivy-discussion-triage'
description: 'automatic triage of Trivy discussions'
inputs:
  discussion_num:
    description: 'which discussion to triage'
    required: false
runs:
  using: "composite"
  steps:
    - name: Conditionally label discussions based on category and content
      env:
        GH_TOKEN: ${{ github.token }}
      uses: actions/github-script@v6
      with:
        script: |
          const {detectDiscussionLabels, fetchDiscussion, labelDiscussion } = require('${{ github.action_path }}/helpers.js');
          const config = require('${{ github.action_path }}/config.json');
          let discussion;
          if (${{ inputs.discussion_num }}) {
              discussion = (await api.fetchDiscussion(discussionNum)).repository.discussion;
          } else {
              discussion = context.payload.discussion;
          }
          const labels = detectDiscussionLabels(discussion, config.discussionLabels);
          if labels.length > 0 {
            labelDiscussion(github, discussionId, labels);
          }
