name: 'trivy-discussion-triage'
description: 'automatic triage of Trivy discussions'
runs:
  using: "composite"
  steps:
    - name: Conditionally label discussions based on category and content
      env:
        GH_TOKEN: ${{ github.token }}
      uses: actions/github-script@v6
      with:
        script: |
          const discussion = context.payload.discussion;
          const discussionNumber = discussion.number;
          const category = discussion.category.name;
          const body = discussion.body;

          if (category !== "Ideas") {
            consolt.log("skipping discussion with category ${category} and body ${body}");
          }
          
          if (body.includes("### Scanner\n\nVulnerability")) { }
          
          const query = 'mutation AddLabels($labelId: ID!, $labelableId:ID!) {
            addLabelsToLabelable(
              input: {labelIds: [$labelId], labelableId: $labelableId}
            ) {
              clientMutationId
            }
          }';
          const variables = {
            labelId: '',
            labelableId: ''
          };
          const result = await github.graphqk(query, variables);
          constole.log(result);

              query: 
              await github.request("POST" /graphql",{
                owner: context.repo.owner,
                repo: context.repo.repo,
                discussion_number: discussionNumber,
                labels: ['scan/vulnerability']
              });
              console.log(`Added "scan/vulnerability" label to discussion #${discussionNumber}.`);
            }
          }
