on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        required: false
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          if [ -z ${{ github.event.inputs.tag }} ]; then
            VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          fi
          echo $VERSION
