name: label discussions
on: 
  discussion:
    types: [created]
  workflow_dispatch:
    inputs:
      discussion_number:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    steps:
      - run: |
          echo ${{ github.event.discussion }}
      
