name: label discussions
on:
  discussion:
    types: [created]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/trivy-discussion-labeler
