name: label discussions
on: 
  discussion:
    types: [created]
  workflow_dispatch:
    inputs:
      discussion_number:
        required: true
jobs:
  host:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.discussions.createLabel({
                discussion_number: ${{ github.event.inputs.discussion_number }} || context.discussion.number,
              name: 'needs-triage',
              color: '000000',
              description: 'This discussion needs triage'
            })
