name: Manual workflow
on: 
  workflow_dispatch:
  push:
jobs:
  host:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          mkdir /tmp/tracee && cd /tmp/tracee
          curl -LO https://github.com/aquasecurity/tracee/releases/download/v0.5.1/tracee.tar.gz
          tar -xzf ./tracee.tar.gz
          sudo ./dist/tracee-ebpf -o out-file:/tmp/tracee/output
          sleep 5
      - run: strace ls
      - uses: actions/upload-artifact@v2
        with:
          name: tracee-out
          path: /tmp/tracee/output
      - run: cat /tmp/tracee/output
      
    
          

