name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
jobs:
  greet:
    runs-on: ubuntu-20.04
    steps:
    - name: gh
      run: gh auth login --with-token <(echo $GITHUB_TOKEN) && gh repo view
    - name: git
      run: git tag ${{ github.event.inputs.tag }} && git push origin --tags
