name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
jobs:
  greet:
    runs-on: ubuntu-20.04
    steps:
    - name: gh
      run: gh auth login && gh repo view
    - name: git
      run: git tag t1 && git push origin --tags
