name: Manual workflow
on: workflow_dispatch
jobs:
  host:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          env
          go env
      - run: |
          docker run --entrypoint sh golang:1.16-alpine env; go env
      - run: |
          docker run --entrypoint sh golang:1.16-buster env; go env

