name: Manual workflow
on: 
  workflow_dispatch:
  push:
jobs:
  host:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          docker run --name tracee --rm --privileged -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro -v /tmp/tracee:/tmp/tracee -d aquasec/tracee:latest trace -t event=ptrace -o out-file:./test
      - run: strace ls
      - run: cat ./test
    
          

