name: Manual workflow
on: 
  workflow_dispatch:
  push:
jobs:
  host:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          mkdir /tmp/tracee
          docker run --name tracee --rm --privileged -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro -v /tmp/tracee:/tmp/tracee aquasec/tracee:latest trace -o out-file:/tmp/tracee/output &
          sleep 20
          cat /tmp/tracee/output
      - run: strace ls
      - uses: actions/upload-artifact@v2
        with:
          name: tracee-out
          path: /tmp/tracee/output
      - run: cat /tmp/tracee/output
      
    
          

