name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
jobs:
  greet:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gh auth login
        run:  gh repo view
