name: Manual workflow
on: 
  workflow_dispatch:
  push:
jobs:
  host:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          mkdir /tmp/tracee
          while true; do echo a>>/tmp/test; sleep 1; done &          
      - run: strace ls
      - uses: actions/upload-artifact@v2
        with:
          name: tracee-out
          path: /tmp/tracee/out
      - run: cat /tmp/tracee/out
      
    
          

